---
deployment:
  tasks:
    - export DEPLOYPATH=/home/qzmivzbj/app.msdieu.com
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/rm -rf $DEPLOYPATH/assets
    - /bin/cp -Rf dist/* $DEPLOYPATH
    - /bin/rm -rf $DEPLOYPATH/dist
    - /bin/cp -Rf dist $DEPLOYPATH
    - /bin/cp -f app.js package.json package-lock.json db.json $DEPLOYPATH
