import assert from 'node:assert/strict';
import test from 'node:test';
import { once } from 'node:events';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import express from 'express';
import type { AddressInfo } from 'node:net';
import { createStarterSceneRouter } from './starterSceneRouter';
import { STARTER_PAPERS } from '../../features/starter-scene/types';

test('Starter scene persists dynamic public lists without changing exams or B ownership', async t => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'starter-scene-test-'));
  Object.assign(process.env, { NODE_ENV: 'test', STORAGE_MODE: 'sqlite', SQLITE_DRIVER: 'better-sqlite3', SQLITE_DB_PATH: path.join(root, 'app.sqlite'), SQLITE_ALLOW_CREATE: 'true', SQLITE_ALLOW_JSON_IMPORT: 'false' });
  const storage = await import('../../lib/sqliteStorage'); await storage.initializeSQLiteStorage();
  const db = new storage.SQLiteFirestore();
  for (const paper of STARTER_PAPERS) for (let index = 1; index <= 31; index++) await db.collection('exam_sets').doc(`${paper}-${index}`).set({ moduleId: 'starter', paperId: paper, title: `QA ${paper} ${index}`, ownerId: index <= 25 ? 'teacher-a' : 'teacher-b', status: 'published', visibility: 'public', createdAt: `2026-10-01T00:00:${String(index).padStart(2, '0')}Z`, draftContent: { privateAnswer: 'SECRET' }, shareToken: 'PRIVATE' });
  await db.collection('exam_sets').doc('draft').set({ moduleId: 'starter', paperId: 'listening', ownerId: 'teacher-a', status: 'draft', visibility: 'draft', title: 'Private draft' });
  await db.collection('exam_sets').doc('assignment').set({ moduleId: 'starter', paperId: 'listening', ownerId: 'teacher-a', status: 'published', visibility: 'assignment', title: 'Private assignment' });
  const app = express(); app.use(express.json());
  const auth: express.RequestHandler = (req, res, next) => { const role = req.headers['x-role']; if (!role) { res.sendStatus(401); return; } req.user = { id: role === 'teacher' ? String(req.headers['x-teacher'] || 'teacher-a') : 'admin', role: String(role) } as any; next(); };
  const staff: express.RequestHandler = (req, res, next) => { if (!['teacher', 'super_admin'].includes(req.user?.role || '')) { res.sendStatus(403); return; } next(); };
  app.use('/api', createStarterSceneRouter({ db, authenticateUser: auth, requireStaff: staff }));
  const server = app.listen(0, '127.0.0.1'); await once(server, 'listening');
  t.after(async () => { server.close(); await once(server, 'close'); await storage.closeSQLiteStorage(); });
  const base = `http://127.0.0.1:${(server.address() as AddressInfo).port}/api`;
  const call = async (route: string, role?: string, body?: unknown) => { const response = await fetch(base + route, { method: body === undefined ? 'GET' : 'PUT', headers: { ...(role ? { 'X-Role': role } : {}), 'Content-Type': 'application/json' }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) }); return { status: response.status, data: await response.json().catch(() => null) }; };
  const endpoint = '/admin/starter-scene/listening';
  const snapshot = (await db.collection('exam_sets').get()).docs.map((document: any) => document.data());
  const initial = await call('/starter-scene'); assert.equal(initial.status, 200); assert.equal(initial.data.papers.listening.links.length, 31); assert.equal(initial.data.papers['reading-writing'].links.length, 31);
  assert.equal(initial.data.papers.listening.configured, false); assert.equal((await db.collection('settings').doc('starter-scene-listening-v1').get()).exists, false, 'Public GET must not initialize storage');
  assert.deepEqual(Object.keys(initial.data.papers.listening.links[0]).sort(), ['href', 'id', 'title']); assert.ok(!JSON.stringify(initial.data).includes('SECRET') && !JSON.stringify(initial.data).includes('PRIVATE'));
  assert.equal((await call(endpoint)).status, 401); assert.equal((await call(endpoint, 'student')).status, 403); assert.equal((await call('/admin/starter-scene/writing', 'super_admin')).status, 404);
  const editor = await call(endpoint, 'super_admin'); assert.equal(editor.data.entries.length, 31);
  const entries = editor.data.entries.map(({ id, setId }: any) => ({ id, setId }));
  const twentyFive = entries.slice(0, 25).reverse();
  const saved = await call(endpoint, 'super_admin', { baseRevision: 0, entries: twentyFive }); assert.equal(saved.status, 200); assert.equal(saved.data.revision, 1);
  let catalog = (await call('/starter-scene')).data; assert.equal(catalog.papers.listening.links.length, 25); assert.equal(catalog.papers.listening.links[0].href, '/exams/starter/listening/listening-25');
  assert.equal((await call(endpoint, 'super_admin', { baseRevision: 0, entries })).status, 409);
  const malformed = [null, [{ id: 'bad', setId: 'draft' }], [{ id: 'bad', setId: 'assignment' }], [{ id: 'bad', setId: 'reading-writing-1' }], [{ id: 'bad', setId: 'https://evil.test' }], [{ id: '', setId: 'listening-1' }], [{ id: 'new1', setId: 'listening-1' }, { id: 'new2', setId: 'listening-1' }], Array(1001).fill({ id: 'bad', setId: 'listening-1' })];
  for (const input of malformed) assert.equal((await call(endpoint, 'super_admin', { baseRevision: 1, entries: input })).status, 400);
  const restored = await call(endpoint, 'super_admin', { baseRevision: 1, entries }); assert.equal(restored.status, 200); assert.equal(restored.data.entries.length, 31, 'Lists may exceed 27');
  const unchanged = restored.data.entries.map(({ id, setId }: any) => ({ id, setId }));
  assert.equal((await call(endpoint, 'teacher', { baseRevision: 2, entries: unchanged.filter((entry: any) => entry.setId !== 'listening-31') })).status, 403, 'Cannot remove another teacher link');
  const foreignMoved = [...unchanged]; [foreignMoved[29], foreignMoved[30]] = [foreignMoved[30], foreignMoved[29]];
  assert.equal((await call(endpoint, 'teacher', { baseRevision: 2, entries: foreignMoved })).status, 403);
  const ownRemoved = unchanged.filter((entry: any) => entry.setId !== 'listening-1');
  assert.equal((await call(endpoint, 'teacher', { baseRevision: 2, entries: ownRemoved })).status, 200);
  const foreignEditor = await call(endpoint, 'teacher'); assert.equal(foreignEditor.data.entries.find((entry: any) => entry.setId === 'listening-31').manageable, false);
  const restoreOwn = [...ownRemoved, { id: 'new-own-link', setId: 'listening-1' }];
  const concurrent = await Promise.all([call(endpoint, 'super_admin', { baseRevision: 3, entries: restoreOwn }), call(endpoint, 'super_admin', { baseRevision: 3, entries: restoreOwn })]); assert.deepEqual(concurrent.map(result => result.status).sort(), [200, 409]);
  const persisted = await call(endpoint, 'super_admin'); assert.equal(persisted.data.revision, 4); assert.equal(persisted.data.entries.length, 31);
  assert.deepEqual((await db.collection('exam_sets').get()).docs.map((document: any) => document.data()), snapshot, 'Layout does not mutate any exam');
  await db.collection('exam_sets').doc('listening-3').update({ status: 'archived' });
  catalog = (await call('/starter-scene')).data; assert.equal(catalog.papers.listening.links.length, 30); assert.ok(!catalog.papers.listening.links.some((entry: any) => entry.href.endsWith('/listening-3')));
  const empty = await call(endpoint, 'super_admin', { baseRevision: 4, entries: [] }); assert.equal(empty.status, 200);
  assert.equal((await call('/starter-scene')).data.papers.listening.links.length, 0, 'Explicit empty does not auto-refill');
  await storage.closeSQLiteStorage(); await storage.initializeSQLiteStorage();
  assert.equal((await call('/starter-scene')).data.papers.listening.links.length, 0, 'Persisted layout survives adapter reopen');
  assert.equal((await call('/starter-scene')).data.papers['reading-writing'].links.length, 31, 'Other paper remains untouched');
});
