import React,{useCallback,useEffect,useRef,useState} from 'react';
import {formatBytes} from '../../../shared/maintenance';
import {cleanupCategory,associationKind,hostingStatus,sourceStatus,scanStatus,type HostingEntry,type HostingEvidence,type HostingSummary,type HostingTree,type HostingBackup,type HostingPage,type HostingDeltas} from '../../../shared/hostingInventory';
const date=(value?:string|null)=>value?new Date(value).toLocaleString('vi-VN'):'Chưa có';
type Mode='files'|'backups'|'jobs'|'alerts'|'audit';
export default function HostingInventory({token,mode='files',onManageApplication}:{token:string;mode?:Mode;onManageApplication?:(entry:HostingEntry)=>void}) {
  const [summary,setSummary]=useState<HostingSummary|null>(null),[tree,setTree]=useState<HostingTree|null>(null),[evidence,setEvidence]=useState<HostingEvidence|null>(null);
  const [contents,setContents]=useState<HostingTree|null>(null),[contentsPage,setContentsPage]=useState(1);
  const [backups,setBackups]=useState<HostingPage<HostingBackup>|null>(null),[deltas,setDeltas]=useState<HostingDeltas|null>(null);
  const [parent,setParent]=useState(''),[page,setPage]=useState(1),[evidencePage,setEvidencePage]=useState(1),[deltaPage,setDeltaPage]=useState(1),[backupPage,setBackupPage]=useState(1);
  const [role,setRole]=useState(''),[filter,setFilter]=useState(''),[status,setStatus]=useState(''),[minimum,setMinimum]=useState('0'),[sort,setSort]=useState('size');
  const [error,setError]=useState(''),[notice,setNotice]=useState(''),[pending,setPending]=useState(false),[loading,setLoading]=useState(false);
  const [selected,setSelected]=useState<HostingEntry|null>(null),[showDeltas,setShowDeltas]=useState(false),[revision,setRevision]=useState(0);
  const opener=useRef<HTMLElement|null>(null);
  const inspector=useRef<HTMLHeadingElement>(null),activeScan=summary?.latest;
  const request=useCallback(async<T,>(url:string,body?:unknown,signal?:AbortSignal):Promise<T>=>{
    const res=await fetch('/api/admin/maintenance/inventory'+url,{method:body===undefined?'GET':'POST',signal,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});
    const value=await res.json().catch(()=>({}));if(!res.ok)throw new Error(value.error||'Không đọc được inventory.');return value as T;
  },[token]);
  const refresh=useCallback(async(signal?:AbortSignal)=>{const result=await request<HostingSummary>('/summary',undefined,signal);if(!signal?.aborted)setSummary(result);},[request]);
  useEffect(()=>{const c=new AbortController();void refresh(c.signal).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[refresh,revision]);
  const running=Boolean(activeScan&&['queued','running'].includes(activeScan.status));
  useEffect(()=>{if(!running)return;const c=new AbortController();const timer=setInterval(()=>{if(!document.hidden)void refresh(c.signal).catch(e=>{if(!c.signal.aborted)setError(e.message);});},2500);return()=>{clearInterval(timer);c.abort();};},[running,refresh]);
  useEffect(()=>{setParent('');setPage(1);setSelected(null);setEvidence(null);setEvidencePage(1);setDeltaPage(1);setBackupPage(1);},[activeScan?.id]);
  useEffect(()=>{setPage(1);},[filter,status,role,minimum,sort,parent]);
  useEffect(()=>{setRole('');},[parent]);
  useEffect(()=>{setSelected(null);setEvidence(null);setContents(null);setContentsPage(1);},[mode]);
  useEffect(()=>{if(mode!=='backups'||!activeScan||selected?.type!=='directory'){setContents(null);return;}const c=new AbortController();void request<HostingTree>('/scans/'+activeScan.id+'/tree?parent='+selected.id+'&page='+contentsPage,undefined,c.signal).then(value=>{if(!c.signal.aborted)setContents(value);}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[mode,activeScan?.id,selected,contentsPage,revision,request]);
  useEffect(()=>{
    if(!activeScan?.retained)return;
    const c=new AbortController(),scan=activeScan.id;setLoading(true);
    const params=new URLSearchParams({parent,page:String(page),filter,status,role,minBytes:minimum,sort});
    const endpoint=mode==='files'?'/tree?'+params:mode==='backups'?'/backups?page='+backupPage:'';
    if(!endpoint){setLoading(false);return;}
    const timer=setTimeout(()=>{void request<HostingTree|HostingPage<HostingBackup>>('/scans/'+scan+endpoint,undefined,c.signal)
      .then(value=>{if(!c.signal.aborted){if(mode==='files')setTree(value as HostingTree);else setBackups(value as HostingPage<HostingBackup>);}})
      .catch(e=>{if(!c.signal.aborted)setError(e.message);}).finally(()=>{if(!c.signal.aborted)setLoading(false);});},150);
    return()=>{clearTimeout(timer);c.abort();};
  },[activeScan?.id,activeScan?.retained,activeScan?.status,parent,page,filter,status,role,minimum,sort,backupPage,mode,revision,request]);
  useEffect(()=>{
    if(!activeScan||!selected)return;const c=new AbortController();
    void request<HostingEvidence>('/scans/'+activeScan.id+'/entries/'+selected.id+'/evidence?page='+evidencePage,undefined,c.signal).then(value=>{if(!c.signal.aborted)setEvidence(value);}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();
  },[selected,activeScan?.id,evidencePage,revision,request]);
  useEffect(()=>{if(!showDeltas||!activeScan)return;const c=new AbortController();void request<HostingDeltas>('/scans/'+activeScan.id+'/deltas?page='+deltaPage,undefined,c.signal).then(value=>{if(!c.signal.aborted)setDeltas(value);}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[showDeltas,activeScan?.id,deltaPage,revision,request]);
  useEffect(()=>{if(evidence&&selected)inspector.current?.focus();},[evidence?.entry.id,selected]);
  const act=async(url:string,body:unknown,message:string)=>{setPending(true);setError('');setNotice('');try{await request(url,body);setNotice(message);await refresh();setRevision(r=>r+1);}catch(e){setError(e instanceof Error?e.message:'Tác vụ lỗi.');}finally{setPending(false);}};
  const view=(entry:HostingEntry)=>{opener.current=document.activeElement instanceof HTMLElement?document.activeElement:null;setEvidence(null);setEvidencePage(1);setContentsPage(1);setSelected(entry);};
  const assessment=(entry:HostingEntry)=><><span className="maintenance-cleanup-badge" data-category={entry.cleanup.category}>{cleanupCategory[entry.cleanup.category]}</span><p>{entry.cleanup.reason}</p><small>Tham chiếu: {hostingStatus[entry.status]} · {entry.role}</small></>;
  const owner=(entry:HostingEntry)=><><strong>{entry.association.label}</strong><small>{associationKind[entry.association.kind]}</small>{entry.association.owners.map(name=><small key={name}>{name}</small>)}<small>{entry.association.reason}</small></>;
  const actions=(entry:HostingEntry)=><div className="maintenance-row-actions">{entry.cleanup.applicationId&&onManageApplication&&<button data-kind={entry.cleanup.category==='ready'?'primary':'secondary'} onClick={()=>onManageApplication(entry)}>{entry.cleanup.action==='manage-backup'?'Tải / xác minh backup':entry.cleanup.category==='ready'?'Dọn file này':'Mở file ứng dụng'}</button>}<button data-kind="secondary" data-action="inspect-hosting" onClick={()=>view(entry)}>{entry.cleanup.category==='protected'?'Vì sao bảo vệ':entry.cleanup.category==='ready'?'Chi tiết / bằng chứng':'Xem điều kiện dọn'}</button></div>;
  const controls=<div className="maintenance-actions">
    <button id="hosting-inventory-scan" data-kind="primary" disabled={pending||running||activeScan?.status==='paused'||!summary?.enabled||summary?.executor!=='process'} onClick={()=>void act('/scan',{},'Đã yêu cầu quét metadata toàn tài khoản; chưa xử lý file.')}>Quét toàn tài khoản</button>
    <button data-kind="secondary" disabled={pending} onClick={()=>{setError('');setRevision(r=>r+1);}}>Tải báo cáo hosting</button>
    {activeScan&&running&&<button data-kind="secondary" disabled={pending} onClick={()=>void act('/scans/'+activeScan.id+'/control',{action:'pause'},'Đã yêu cầu dừng ở ranh giới batch.')}>Tạm dừng</button>}
    {activeScan&&['paused','interrupted','failed'].includes(activeScan.status)&&<button data-kind="secondary" disabled={pending||summary?.executor!=='process'} onClick={()=>void act('/scans/'+activeScan.id+'/control',{action:'resume'},'Đã yêu cầu tiếp tục từ hàng chờ bền vững.')}>Tiếp tục</button>}
    {activeScan&&!['completed','cancelled'].includes(activeScan.status)&&<button data-kind="secondary" disabled={pending} onClick={()=>void act('/scans/'+activeScan.id+'/control',{action:'cancel'},'Đã yêu cầu hủy kiểm kê; các file nguồn vẫn được giữ.')}>Hủy quét</button>}
  </div>;
  const pagination=(p:number,pages:number,total:number,change:(n:number)=>void)=><div className="maintenance-pagination"><button data-kind="secondary" disabled={loading||p<=1} onClick={()=>change(p-1)}>Trang trước</button><span>{p}/{pages} · {total.toLocaleString('vi-VN')} mục</span><button data-kind="secondary" disabled={loading||p>=pages} onClick={()=>change(p+1)}>Trang sau</button></div>;
  return <section className="maintenance-card hosting-inventory" aria-label="Kiểm kê hosting">
    <h3>{mode==='files'?'Thư mục hosting':mode==='backups'?'Bộ backup đã có trên hosting':mode==='jobs'?'Cấu hình và tiến độ tác vụ hosting':mode==='audit'?'Nhật ký kiểm kê hosting':'Phát sinh và cảnh báo hosting'}</h3>
    {(mode==='files'||mode==='backups'||mode==='jobs')&&controls}
    {error&&<p role="alert" className="maintenance-error">{error}</p>}{notice&&<p role="status" className="maintenance-notice">{notice}</p>}
    {!summary&&!error&&<p role="status">Đang tải báo cáo cached…</p>}
    {summary&&<>
      <p className="hosting-path">Phạm vi đăng ký: <strong>{summary.root}</strong></p>
      {summary.executor!=='process'&&<p className="maintenance-alert warning">Executor chưa cấu hình. Server cần bật process sau kiểm tra khả năng host, hoặc chạy CLI inventory. Mở trang không kích hoạt quét.</p>}
      {mode==='jobs'&&!activeScan&&<p>Collector: lịch thủ công, executor {summary.executor==='process'?'process đã cấu hình':'chưa cấu hình'}. Cron/Speaking cần được quan sát trong lượt kiểm kê, chưa có bằng chứng chạy.</p>}
      {!activeScan&&<p>Chưa quét toàn tài khoản. Báo cáo file ứng dụng và quota cũ là nguồn riêng.</p>}
      {activeScan&&<>
        {activeScan.scope!==summary.scope&&<p className="maintenance-alert warning">Phạm vi hoặc cách kiểm tra đã đổi. Nếu lượt cũ đang tạm dừng, chọn Hủy quét rồi quét mới để đối chiếu.</p>}
        {(mode==='files'||mode==='jobs'||mode==='backups')&&<div className="hosting-progress" role="status"><strong>{scanStatus[activeScan.status]||activeScan.status}</strong> · {{queued:'Đang chờ',sources:'Đọc nguồn phụ thuộc',filesystem:'Đọc thư mục',aggregate:'Tổng hợp',complete:'Hoàn tất'}[activeScan.phase]||activeScan.phase} · {activeScan.fileCount.toLocaleString('vi-VN')} file / {activeScan.directoryCount.toLocaleString('vi-VN')} thư mục
          <small>Bắt đầu {date(activeScan.startedAt)} · heartbeat {date(activeScan.heartbeat)} · kết thúc {date(activeScan.finishedAt)}</small><small>{running?'Đang xét':'Thư mục xét gần nhất'}: {activeScan.currentPath||'Gốc tài khoản'}{activeScan.reason?' · '+activeScan.reason:''}</small>
        </div>}
        {mode==='files'&&<>
          <div className="maintenance-metrics"><article><span>Dung lượng theo đường dẫn</span><strong>{formatBytes(activeScan.logicalBytes)}</strong><small>Cha đã gồm con; chỉ cộng file thường</small></article><article><span>Dung lượng file duy nhất</span><strong>{formatBytes(activeScan.uniqueBytes)}</strong><small>Không cộng đôi hardlink; hoàn tất mới tổng hợp</small></article><article><span>Allocated bytes</span><strong>{activeScan.allocatedBytes===null?'Chưa hỗ trợ/đủ số liệu':formatBytes(activeScan.allocatedBytes)}</strong><small>Blocks filesystem; khác quota cPanel</small></article><article><span>Chỉ mục quản trị</span><strong>{formatBytes(summary.storage?.bytes)}</strong><small>Ngân sách {formatBytes(summary.storage?.limitBytes)} · tách khỏi cây nguồn</small></article></div>
          <p>Filesystem: {activeScan.filesystemComplete?'Đọc đủ phạm vi quan sát':'Chưa đầy đủ'} · Phụ thuộc: {activeScan.dependencyComplete?'Đủ các nguồn đã đăng ký':'Còn thiếu nguồn/bằng chứng'}. Đây là cửa sổ quan sát, file có thể đổi trong khi quét.</p>
          <details><summary>Vai trò và trạng thái hosting</summary><p>Được bảo vệ: vùng dữ liệu/hệ thống hoặc policy cần giữ. Đang được tham chiếu: có đường dẫn/quan hệ cấu hình, chưa khẳng định mọi file đang chạy. Chưa xác minh: thiếu chứng cứ. Ứng viên: cần xem xét thêm. Đã xác minh theo chính sách: chỉ verifier đúng nhóm mới cấp; V1 chưa cấp quyền này cho thư mục hosting.</p><p>Khả năng dọn tách riêng: Có thể dọn có xác nhận / Cần xem xét / Được bảo vệ / Chưa đủ xác minh. File khớp báo cáo ứng dụng có nút mở thao tác dọn đã có. Thư mục hoặc file chưa có verifier chỉ hiển thị điều kiện còn thiếu; không cấp xóa theo tên.</p></details>
          <div className="maintenance-filters"><label>Tìm trong thư mục<input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Tên file hoặc thư mục"/></label><label>Trạng thái tham chiếu<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Tất cả</option>{Object.entries(hostingStatus).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>Vai trò<select value={role} onChange={e=>setRole(e.target.value)}><option value="">Tất cả</option>{tree?.roles.map(r=><option key={r} value={r}>{r}</option>)}</select></label><label>Dung lượng tối thiểu<select value={minimum} onChange={e=>setMinimum(e.target.value)}><option value="0">Tất cả</option><option value="1048576">1 MiB</option><option value="104857600">100 MiB</option></select></label><label>Sắp xếp<select value={sort} onChange={e=>setSort(e.target.value)}><option value="size">Dung lượng giảm dần</option><option value="name">Tên</option></select></label></div>
          <nav className="hosting-breadcrumbs" aria-label="Cây thư mục">{tree?.breadcrumbs.map((c,i)=><React.Fragment key={c.id}>{i>0&&<span>/</span>}<button data-kind="secondary" aria-current={i===tree.breadcrumbs.length-1?'location':undefined} onClick={()=>{setParent(c.relative?c.id:'');setPage(1);}}>{c.name}</button></React.Fragment>)}</nav>
          {loading&&<p role="status">Đang đọc trang chỉ mục…</p>}
          <p className="maintenance-muted">Mỗi mục có hai kết luận riêng: thuộc dự án/dịch vụ nào và có thể dọn đến bước nào. Cột thao tác chỉ mở hành động đã có bộ kiểm tra.</p><div className="maintenance-table"><table><thead><tr><th>Thư mục / file</th><th>Dung lượng</th><th>Dự án / dịch vụ liên quan</th><th>Khả năng dọn</th><th>Thao tác</th></tr></thead><tbody>{tree?.items.map(e=><tr key={e.id}><td>{e.type==='directory'?<button data-kind="secondary" disabled={Boolean(e.issue)} onClick={()=>{setParent(e.id);setPage(1);}}>{e.name}/</button>:<strong>{e.name}</strong>}<small>{e.relative} · {e.type}</small>{e.issue&&<small>Coverage: {e.issue}</small>}</td><td>{formatBytes(e.bytes)}<small>{e.type==='directory'?e.fileCount+' file / '+e.directoryCount+' thư mục':date(e.modifiedAt)}</small></td><td>{owner(e)}</td><td>{assessment(e)}</td><td>{actions(e)}</td></tr>)}{!loading&&!tree?.items.length&&<tr><td colSpan={5}>Không có mục trong trang/bộ lọc hiện tại; không suy ra file đã mất.</td></tr>}</tbody></table></div>
          {tree&&pagination(page,tree.pages,tree.total,setPage)}
        </>}
        {mode==='backups'&&<><p>Quét toàn tài khoản sẽ tìm các bộ/thành phần có dấu hiệu backup ngoài thư mục dự án. Tên/vị trí chưa chứng minh backup đầy đủ hoặc tải được để phục hồi. V1 hiển thị kiểm kê; tải/xóa bộ mới thuộc V2.</p><div className="maintenance-table"><table><thead><tr><th>Bộ / thành phần</th><th>Dung lượng / loại</th><th>Mức xác minh</th><th>Chi tiết</th></tr></thead><tbody>{backups?.items.map(e=><tr key={e.id}><td><strong>{e.name}</strong><small>{e.relative}</small><p>{e.recognition}</p></td><td>{formatBytes(e.bytes)}<small>{e.kind} · {e.fileCount} file con</small></td><td>Thành phần: quan sát được<small>Format / restore / ngoài host: chưa xác minh</small>{e.mayBeWriting&&<small>File mới thay đổi; có thể đang ghi</small>}</td><td><button data-kind="secondary" onClick={()=>view(e)}>Xem thành phần / bằng chứng</button></td></tr>)}{!backups?.items.length&&<tr><td colSpan={4}>Chưa có bộ backup trong chỉ mục hiện tại.</td></tr>}</tbody></table></div>{backups&&pagination(backupPage,backups.pages,backups.total,setBackupPage)}</>}
        {mode==='jobs'&&<><h4>Tác vụ đã đăng ký / nguồn được quan sát</h4><div className="maintenance-table"><table><thead><tr><th>Tác vụ / executor</th><th>Cấu hình / lịch</th><th>Bằng chứng thực thi</th></tr></thead><tbody>{activeScan.tasks.map(t=><tr key={t.id}><td>{t.task}<small>{t.source} · {t.executor}</small></td><td>{{configured:'Đã cấu hình',manual:'Chạy thủ công',observed:'Quan sát được'}[t.configuration]||t.configuration}<small>{t.schedule} · {t.timezone}</small></td><td>{t.execution==='verified'?'Có tiến độ executor':t.execution==='observed'?'Trạng thái lưu trong nguồn':'Chưa có bằng chứng chạy'}<small>{t.reason}</small>{t.counts?.map(c=><small key={c.status}>{c.status}: {c.count}</small>)}</td></tr>)}</tbody></table></div><h4>Lịch sử quét hosting</h4><div className="maintenance-table"><table><thead><tr><th>Thời điểm</th><th>Trạng thái / coverage</th><th>Kết quả</th></tr></thead><tbody>{summary.scans.map(s=><tr key={s.id}><td>{date(s.startedAt)}<small>{s.id}</small></td><td>{scanStatus[s.status]}<small>Filesystem: {s.filesystemComplete?'đủ':'partial'} · phụ thuộc: {s.dependencyComplete?'đủ':'chưa đủ'}</small></td><td>{s.fileCount} file · {formatBytes(s.logicalBytes)}<small>{s.reason}</small></td></tr>)}</tbody></table></div></>}
        {(mode==='files'||mode==='jobs')&&<details className="hosting-sources"><summary>Nguồn phụ thuộc và phần chưa xác minh ({activeScan.sources.filter(s=>s.status!=='available').length})</summary>{activeScan.sources.map(s=><article key={s.id}><strong>{s.label}: {sourceStatus[s.status]||s.status}</strong><p>{s.reason}</p><small>{date(s.at)} · {s.version}</small></article>)}</details>}
        {(mode==='files'||mode==='alerts')&&<><h4>Tăng trưởng cùng phạm vi</h4><div className="hosting-growth">{summary.growth.map(g=><p key={g.days}>{g.days} ngày: <strong>{g.bytes===null?'Chưa đủ mốc':formatBytes(g.bytes)}</strong><small>{g.reason}</small></p>)}</div>{activeScan.alerts.map(a=><p key={a.key} className={'maintenance-alert '+a.severity}>{a.message}</p>)}<button data-kind="secondary" aria-expanded={showDeltas} onClick={()=>setShowDeltas(v=>!v)}>{showDeltas?'Ẩn thay đổi file':'Xem thay đổi file'}</button>{showDeltas&&<>{!deltas?.comparable&&<p>Chưa có hai mốc filesystem đầy đủ cùng scope để kết luận thay đổi.</p>}<div className="maintenance-table"><table><thead><tr><th>File</th><th>Thay đổi quan sát</th><th>Trước / sau</th><th>Nguồn tạo</th></tr></thead><tbody>{deltas?.items.map(d=><tr key={d.rel}><td>{d.rel}</td><td>{d.kind==='observed_new'?'Mới được thấy':d.kind==='not_observed'?'Không còn được thấy':'Metadata đổi'}</td><td>{d.before_bytes===null?'—':formatBytes(d.before_bytes)} / {d.after_bytes===null?'—':formatBytes(d.after_bytes)}</td><td>{d.attribution==='path_time_correlation'?'Tương quan đường dẫn/thời gian writer ứng dụng; chưa chứng minh ai tạo':'Chưa xác định; chưa có event gắn file'}</td></tr>)}</tbody></table></div>{deltas&&pagination(deltaPage,deltas.pages,deltas.total,setDeltaPage)}</>}</>}
      </>}
      {mode==='audit'&&<div className="maintenance-table"><table><thead><tr><th>Thời gian / actor</th><th>Hành động</th><th>Chi tiết</th></tr></thead><tbody>{summary.audit.map(a=><tr key={a.id}><td>{date(a.at)}<small>{a.actor}</small></td><td>{a.action}<small>{a.scan}</small></td><td>{a.reason}</td></tr>)}{!summary.audit.length&&<tr><td colSpan={3}>Chưa có nhật ký kiểm kê.</td></tr>}</tbody></table></div>}
    </>}
    {selected&&<section className="hosting-inspector" aria-label="Bằng chứng đối tượng"><div className="maintenance-actions"><h4 ref={inspector} tabIndex={-1}>Bằng chứng: {selected.name}</h4><button data-kind="secondary" onClick={()=>{setSelected(null);setEvidence(null);opener.current?.focus();}}>Đóng bằng chứng</button></div>
      {!evidence&&<p role="status">Đang đọc bằng chứng…</p>}{evidence&&<><p>{evidence.entry.relative} · {hostingStatus[evidence.entry.status]} · {evidence.entry.role}</p><div className="hosting-decision"><h4>Khả năng dọn và quan hệ</h4>{owner(evidence.entry)}{assessment(evidence.entry)}<ol>{evidence.entry.cleanup.nextSteps.map(step=><li key={step}>{step}</li>)}</ol>{evidence.entry.cleanup.applicationId&&onManageApplication&&<button data-kind={evidence.entry.cleanup.category==='ready'?'primary':'secondary'} onClick={()=>onManageApplication(evidence.entry)}>{evidence.entry.cleanup.action==='manage-backup'?'Tải / xác minh backup':'Mở thao tác file ứng dụng'}</button>}</div><p>Quan sát {date(evidence.at)}. {evidence.scopeChanged?'Phạm vi hoặc cách kiểm tra đã đổi; cần quét mới.':''}</p><button data-kind="secondary" disabled={pending||running||evidence.scopeChanged} onClick={()=>void act('/scans/'+activeScan!.id+'/entries/'+selected.id+'/reverify',{},'Đã đọc lại nguồn và fingerprint đối tượng; chưa cấp quyền xóa.')}>Xác minh lại nguồn</button>
        {mode==='backups'&&contents&&<><h4>Thành phần được quan sát trong thư mục</h4><div className="maintenance-table"><table><thead><tr><th>Thành phần</th><th>Dung lượng</th><th>Chi tiết</th></tr></thead><tbody>{contents.items.map(c=><tr key={c.id}><td>{c.name}{c.type==='directory'?'/':''}<small>{c.relative}</small></td><td>{formatBytes(c.bytes)}</td><td><button data-kind="secondary" onClick={()=>view(c)}>Xem chi tiết</button></td></tr>)}</tbody></table></div>{pagination(contentsPage,contents.pages,contents.total,setContentsPage)}</>}
        <div className="hosting-edges">{evidence.edges.map(e=><article key={e.id}><strong>{e.from_node} → {e.to_node}</strong><p>{e.relation} · {e.source} · {sourceStatus[e.status]}</p><small>{e.reason} · {date(e.at)} · {e.version}</small></article>)}{!evidence.edges.length&&<p>Chưa có cạnh phụ thuộc được nhận diện cho mục này. Điều này chưa chứng minh file không còn tác dụng.</p>}</div>{pagination(evidencePage,evidence.pages,evidence.total,setEvidencePage)}<h4>Nguồn còn thiếu</h4>{evidence.sources.filter(s=>s.status!=='available').map(s=><p key={s.id}>{s.label}: {sourceStatus[s.status]} · {s.reason}</p>)}</>}
    </section>}
  </section>;
}