import React, { useEffect, useRef, useState } from 'react';
import { KIND_LABELS, MAX_READING_ITEMS, lessonItems, normalizeLesson, SpeakingError, type ReadingItem, type Lesson, type LessonInput, type Capabilities, type ResultSummary, type SpeakingReviewData } from '../../shared/speaking/types';
import type { VocabSet } from '../../types';
import { resolveTtsPlaybackRate } from '../../lib/game-engine/speech';
import { adminRequest, request } from './api';
import SpeakingReview from './Review';
import SampleAudio from './SampleAudio';
import './speaking.css';
const blankItem = (): ReadingItem => ({ id: '', referenceText: '', sampleAudioUrl: '', samplePlaybackRate: 1 });
const newDraft = (): LessonInput => ({ title: '', referenceText: '', partnerText: '', instructions: '', kind: 'word', locale: 'en-US', grade: 3, maxSeconds: 8, provider: 'azure', sampleAudioUrl: '', samplePlaybackRate: 1, feedbackEnabled: false, items: [blankItem()] });
type Results = { items: ResultSummary[]; page: number; pageSize: number; total: number };
export default function SpeakingAdmin({ token }: { token: string }) {
  const [tab, setTab] = useState<'lessons' | 'editor' | 'results' | 'config'>('lessons'), [lessons, setLessons] = useState<Lesson[]>([]), [draft, setDraft] = useState<LessonInput>(newDraft), [editing, setEditing] = useState<Lesson | null>(null), [caps, setCaps] = useState<Capabilities | null>(null);
  const [error, setError] = useState(''), [notice, setNotice] = useState(''), [busy, setBusy] = useState(false), [results, setResults] = useState<Results | null>(null), [grade, setGrade] = useState(''), [kind, setKind] = useState(''), [page, setPage] = useState(1), [review, setReview] = useState<SpeakingReviewData | null>(null);
  const [search, setSearch] = useState(''), [catalogPage, setCatalogPage] = useState(1), [catalogTotal, setCatalogTotal] = useState(0), [bulkText, setBulkText] = useState(''), [sourceSets, setSourceSets] = useState<VocabSet[] | null>(null), [sourceId, setSourceId] = useState('');
  const setMode = draft.kind === 'word' || draft.kind === 'sentence';
  const editorFeedback = useRef<HTMLDivElement>(null);
  const reload = async (query = search, targetPage = catalogPage) => { const data = await adminRequest<{ items: Lesson[]; total: number }>(token, '/admin/lessons-page?' + new URLSearchParams({ search: query, page: String(targetPage) })); setLessons(data.items); setCatalogTotal(data.total); };
  useEffect(() => { let live = true; void request<Capabilities>('/capabilities').then(data => { if (live) setCaps(data); }).catch(e => { if (live) setError(e.message); }); return () => { live = false; }; }, [token]);
  useEffect(() => { let live = true; const timer = setTimeout(() => { void adminRequest<{ items: Lesson[]; total: number }>(token, '/admin/lessons-page?' + new URLSearchParams({ search, page: String(catalogPage) })).then(data => { if (live) { setLessons(data.items); setCatalogTotal(data.total); } }).catch(e => { if (live) setError(e.message); }); }, 250); return () => { live = false; clearTimeout(timer); }; }, [token, search, catalogPage]);
  useEffect(() => { if (tab !== 'results') return; let live = true; setReview(null); void adminRequest<Results>(token, `/admin/results?${new URLSearchParams({ grade, kind, page: String(page) })}`).then(data => { if (live) setResults(data); }).catch(e => { if (live) setError(e.message); }); return () => { live = false; }; }, [token, tab, grade, kind, page]);
  const perform = async (work: () => Promise<void>) => { if (busy) return; setBusy(true); setError(''); setNotice(''); try { await work(); } catch (e) { const hint = e instanceof SpeakingError && e.code === 'INVALID_REFERENCE' && draft.kind === 'word' ? ' Nếu đọc cả câu, chọn Dạng bài: Câu rồi lưu lại; nội dung đang soạn được giữ nguyên.' : ''; setError((e instanceof Error ? e.message : 'Không thể xử lý.') + hint); requestAnimationFrame(() => editorFeedback.current?.focus()); } finally { setBusy(false); } };
  const change = <K extends keyof LessonInput>(key: K, value: LessonInput[K]) => setDraft(current => ({ ...current, [key]: value, ...(['referenceText', 'locale'].includes(key) ? { sampleAudioUrl: '', samplePlaybackRate: 1, ...(current.items ? { items: current.items.map(i => ({ ...i, sampleAudioUrl: '', samplePlaybackRate: 1 })) } : {}) } : {}) }));
  const changeItems = (items: ReadingItem[]) => setDraft(current => ({ ...current, items, referenceText: items[0]?.referenceText || '', sampleAudioUrl: items[0]?.sampleAudioUrl || '', samplePlaybackRate: items[0]?.samplePlaybackRate || 1 }));
  const changeItem = (index: number, value: Partial<ReadingItem>) => changeItems((draft.items || []).map((item, i) => i === index ? { ...item, ...value } : item));
  const changeKind = (next: LessonInput['kind']) => setDraft(current => ({ ...current, kind: next, maxSeconds: next === 'word' ? 8 : next === 'passage' ? 180 : 30, items: next === 'word' || next === 'sentence' ? current.items || lessonItems(current) : undefined }));
  const persistDraft = async () => { const input = normalizeLesson(draft); const lesson = await adminRequest<Lesson>(token, editing ? `/admin/lessons/${editing.id}` : '/admin/lessons', editing ? 'PUT' : 'POST', { ...input, revision: editing?.revision }); setEditing(lesson); setDraft(lesson); return lesson; };
  const refreshSaved = async (message: string) => { setSearch(''); setCatalogPage(1); setNotice(message); try { await reload('', 1); } catch { setNotice(message + ' Chưa tải lại được kho; bài đã lưu, hãy mở Kho bài để tải lại.'); } };
  const save = () => perform(async () => { await persistDraft(); await refreshSaved('Đã lưu bản nháp vào Kho bài. Có thể tiếp tục sửa hoặc Xuất bản cho học sinh.'); });
  const publish = () => perform(async () => { const lesson = !editing || JSON.stringify(draft) !== JSON.stringify(editing) ? await persistDraft() : editing; const next = await adminRequest<Lesson>(token, `/admin/lessons/${lesson.id}/publish`, 'POST', { revision: lesson.revision }); setEditing(next); setDraft(next); await refreshSaved('Đã xuất bản bài luyện đọc.'); });
  const append = (values: ReadingItem[]) => { const current = (draft.items || []).filter(item => item.referenceText.trim()); if (current.length + values.length > MAX_READING_ITEMS) throw new Error(`Một bộ tối đa ${MAX_READING_ITEMS} mục. Nội dung hiện tại được giữ nguyên.`); changeItems([...current, ...values]); };
  const sample = (item: ReadingItem, index?: number) => perform(async () => {
    const input = normalizeLesson({ ...draft, title: draft.title || 'Audio mẫu', items: undefined, referenceText: item.referenceText, sampleAudioUrl: item.sampleAudioUrl, samplePlaybackRate: item.samplePlaybackRate });
    const result = await adminRequest<{ audioUrl: string; playbackRate: number; warnings?: string[] }>(token, '/admin/sample', 'POST', input);
    if (index !== undefined) changeItem(index, { sampleAudioUrl: result.audioUrl, samplePlaybackRate: result.playbackRate }); else setDraft(v => ({ ...v, sampleAudioUrl: result.audioUrl, samplePlaybackRate: result.playbackRate }));
    setNotice(result.warnings?.join(' ') || 'Đã tạo audio mẫu. Lưu bài để giữ audio.');
  });
  const audioEditor = (item: ReadingItem, index?: number) => <div className="speaking-audio-editor"><label>Đường dẫn audio mẫu{index === undefined ? '' : ` (mục ${index + 1})`}<input disabled={busy} value={item.sampleAudioUrl} maxLength={250} onChange={e => index === undefined ? setDraft(v => ({ ...v, sampleAudioUrl: e.target.value })) : changeItem(index, { sampleAudioUrl: e.target.value })} placeholder="/audio/…mp3" /></label><div className="speaking-actions"><button type="button" disabled={busy || !item.referenceText.trim() || caps?.sampleTts?.configured !== true} title={caps?.sampleTts?.reason || (!caps ? 'Đang kiểm tra cấu hình audio mẫu.' : undefined)} onClick={() => void sample(item, index)}>Tạo audio mẫu</button>{item.sampleAudioUrl && <button type="button" disabled={busy} onClick={() => index === undefined ? setDraft(v => ({ ...v, sampleAudioUrl: '' })) : changeItem(index, { sampleAudioUrl: '' })}>Gỡ audio khỏi mục</button>}</div>{caps?.sampleTts?.configured === false && <p className="speaking-audio-hint">{caps.sampleTts.reason}</p>}<SampleAudio text={item.referenceText} locale={draft.locale} url={/^\/audio\/[A-Za-z0-9_-]+\.(mp3|wav|ogg)$/i.test(item.sampleAudioUrl) ? item.sampleAudioUrl : ''} rate={item.samplePlaybackRate} disabled={busy} /></div>;
  return <section id="speaking-admin"><h1>Speaking / Luyện đọc</h1><p>Soạn bộ từ/câu hoặc bài hội thoại/đoạn văn, cho học sinh đọc từng mục và xem kết quả.</p>
    <nav className="speaking-actions" aria-label="Quản lý Speaking">{([['lessons', 'Kho bài'], ['editor', 'Soạn bài'], ['results', 'Kết quả'], ['config', 'Cấu hình dịch vụ']] as const).map(([id, label]) => <button type="button" className={tab === id ? 'speaking-primary' : ''} aria-current={tab === id ? 'page' : undefined} key={id} onClick={() => { setTab(id); setError(''); setNotice(''); }}>{label}</button>)}</nav>
    {tab !== 'editor' && error && <p role="alert" className="speaking-error">{error}</p>}{tab !== 'editor' && notice && <p role="status">{notice}</p>}
    {caps && !caps.providers.some(p => p.configured) && <p className="speaking-alert">Chưa có khóa chấm giọng. Có thể soạn và xuất bản bài; chấm thật sẽ hoạt động sau khi cấu hình backend và khởi động lại.</p>}
    {tab === 'lessons' && <><label className="speaking-form">Tìm trong kho bài<input type="search" value={search} maxLength={200} onChange={e => { setSearch(e.target.value); setCatalogPage(1); }} /></label>{!lessons.length && <p>Chưa có bài trong phạm vi quản lý.</p>}{lessons.map(lesson => <article className="speaking-card" key={lesson.id}><h2>{lesson.title}</h2><p>{KIND_LABELS[lesson.kind]} · {lessonItems(lesson).length} mục · Lớp {lesson.grade} · {lesson.status === 'published' ? 'Đã xuất bản' : 'Bản nháp'}</p><div className="speaking-actions"><button type="button" disabled={busy} onClick={() => { setEditing(lesson); setDraft(lesson.kind === 'word' || lesson.kind === 'sentence' ? { ...lesson, items: lessonItems(lesson) } : lesson); setTab('editor'); setBulkText(''); setError(''); }}>Sửa</button><button type="button" disabled={busy} onClick={() => void perform(async () => { await adminRequest(token, `/admin/lessons/${lesson.id}`, 'DELETE', { revision: lesson.revision }); await reload(); setNotice('Đã lưu trữ bài. Kết quả cũ vẫn được giữ.'); })}>Lưu trữ</button><a href={`/speaking/lesson/${lesson.id}`} target="_blank" rel="noreferrer">Xem bài học sinh</a></div></article>)}<div className="speaking-actions"><button type="button" disabled={catalogPage <= 1} onClick={() => setCatalogPage(p => p - 1)}>Trang trước</button><span>Trang {catalogPage} · {catalogTotal} bài</span><button type="button" disabled={catalogPage * 30 >= catalogTotal} onClick={() => setCatalogPage(p => p + 1)}>Trang sau</button></div></>}
    {tab === 'editor' && <form className="speaking-form speaking-card" noValidate onSubmit={e => { e.preventDefault(); void save(); }}><h2>{editing ? `Sửa bài · Phiên bản ${editing.revision}` : 'Bài mới'}</h2><label>Tiêu đề<input disabled={busy} required maxLength={200} value={draft.title} onChange={e => change('title', e.target.value)} /></label>
      <div className="speaking-grid"><label>Dạng bài<select disabled={busy} value={draft.kind} onChange={e => changeKind(e.target.value as LessonInput['kind'])}>{Object.entries(KIND_LABELS).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></label><label>Lớp<select disabled={busy} value={draft.grade} onChange={e => change('grade', Number(e.target.value))}>{Array.from({ length: 9 }, (_, i) => <option key={i} value={i + 1}>Lớp {i + 1}</option>)}</select></label><label>Giọng đọc<select disabled={busy} value={draft.locale} onChange={e => change('locale', e.target.value as LessonInput['locale'])}><option value="en-US">Anh-Mỹ (en-US)</option><option value="en-GB">Anh-Anh (en-GB)</option></select></label><label>Dịch vụ chấm<select disabled={busy} value={draft.provider} onChange={e => change('provider', e.target.value as LessonInput['provider'])}><option value="azure">Azure Speech (mặc định)</option><option value="speechsuper">SpeechSuper (đối chiếu)</option></select></label><label>Thời lượng mỗi mục (giây)<input disabled={busy} type="number" min={1} max={draft.kind === 'word' ? 8 : draft.kind === 'passage' ? draft.provider === 'speechsuper' ? 180 : 300 : 30} value={draft.maxSeconds} onChange={e => change('maxSeconds', Number(e.target.value))} /></label></div>
      {caps?.sampleTts?.configured === false && <p className="speaking-alert">{caps.sampleTts.reason}</p>}
      {setMode ? <><h3>{draft.kind === 'word' ? 'Danh sách từ vựng' : 'Danh sách câu'} · {draft.items?.length || 0}/{MAX_READING_ITEMS}</h3><p>Mỗi mục là một lượt thu âm và chấm riêng. Một từ cho mỗi mục từ vựng; mỗi câu có thể chứa nhiều từ.</p>
        <div className="speaking-card"><label>Dán danh sách — mỗi dòng một {draft.kind === 'word' ? 'từ' : 'câu'}<textarea disabled={busy} rows={3} maxLength={20000} value={bulkText} onChange={e => setBulkText(e.target.value)} /></label><button type="button" disabled={busy || !bulkText.trim()} onClick={() => void perform(async () => { append(bulkText.split(/\r?\n/).map(s => s.trim()).filter(Boolean).map(referenceText => ({ ...blankItem(), referenceText }))); setBulkText(''); setNotice('Đã thêm danh sách. Xem lại từng mục trước khi lưu.'); })}>Thêm danh sách</button>
          {draft.kind === 'word' && <><div className="speaking-actions"><button type="button" disabled={busy} onClick={() => void perform(async () => { const response = await fetch('/api/vocab-sets', { headers: { Authorization: `Bearer ${token}` } }); if (!response.ok) throw new Error('Không tải được kho từ vựng của B.'); setSourceSets(await response.json()); })}>Chọn từ bộ từ vựng B</button></div>{sourceSets && <><label>Bộ từ vựng nguồn<select disabled={busy} value={sourceId} onChange={e => setSourceId(e.target.value)}><option value="">Chọn bộ</option>{sourceSets.map(set => <option key={set.id} value={set.id}>{set.title}</option>)}</select></label><button type="button" disabled={busy || !sourceId} onClick={() => void perform(async () => { const source = sourceSets.find(s => s.id === sourceId); if (!source) return; append((source.items || []).map(item => ({ ...blankItem(), referenceText: item.term, sampleAudioUrl: (!item.ttsLang || item.ttsLang === draft.locale) && /^\/audio\/[A-Za-z0-9_-]+\.(mp3|wav|ogg)(\?v=\d+)?$/i.test(item.audioUrl || '') ? (item.audioUrl || '').replace(/\?v=\d+$/, '') : '', samplePlaybackRate: resolveTtsPlaybackRate(item.ttsProvider, item.ttsSpeed) }))); setNotice('Đã sao chép từ và audio phù hợp. Kho từ vựng B giữ nguyên; kiểm tra các mục trước khi lưu.'); })}>Thêm từ của bộ đã chọn</button></>}</>}
        </div>
        {(draft.items || []).map((item, index) => <section key={index} className="speaking-item-editor"><h4>Mục {index + 1}</h4><label>Nội dung cần đọc (mục {index + 1}){draft.kind === 'word' ? <input disabled={busy} required maxLength={150} value={item.referenceText} onChange={e => changeItem(index, { referenceText: e.target.value, sampleAudioUrl: '', samplePlaybackRate: 1 })} /> : <textarea disabled={busy} required rows={2} maxLength={6000} value={item.referenceText} onChange={e => changeItem(index, { referenceText: e.target.value, sampleAudioUrl: '', samplePlaybackRate: 1 })} />}</label>{audioEditor(item, index)}<div className="speaking-actions"><button type="button" disabled={busy || index === 0} onClick={() => { const items = [...draft.items!]; [items[index - 1], items[index]] = [items[index], items[index - 1]]; changeItems(items); }}>Lên</button><button type="button" disabled={busy || index === draft.items!.length - 1} onClick={() => { const items = [...draft.items!]; [items[index], items[index + 1]] = [items[index + 1], items[index]]; changeItems(items); }}>Xuống</button><button type="button" disabled={busy || draft.items!.length <= 1} onClick={() => changeItems(draft.items!.filter((_, i) => i !== index))}>Gỡ mục {index + 1}</button></div></section>)}<button type="button" disabled={busy || (draft.items?.length || 0) >= MAX_READING_ITEMS} onClick={() => changeItems([...(draft.items || []), blankItem()])}>Thêm mục</button></> : <>
        {draft.kind === 'dialogue' && <label>Lời của vai đối thoại (không chấm)<textarea disabled={busy} value={draft.partnerText} maxLength={3000} onChange={e => change('partnerText', e.target.value)} /></label>}<label>{draft.kind === 'dialogue' ? 'Lời học sinh cần đọc trong lượt này' : 'Nội dung cần đọc'}<textarea disabled={busy} required rows={8} maxLength={6000} value={draft.referenceText} onChange={e => change('referenceText', e.target.value)} /></label><p>Đoạn văn tối đa 400 từ; hội thoại chỉ chấm vai học sinh trong một lượt.</p>{audioEditor({ id: '1', referenceText: draft.referenceText, sampleAudioUrl: draft.sampleAudioUrl, samplePlaybackRate: draft.samplePlaybackRate })}</>}
      <label>Hướng dẫn<textarea disabled={busy} maxLength={2000} value={draft.instructions} onChange={e => change('instructions', e.target.value)} /></label><label><span><input disabled={busy} type="checkbox" checked={draft.feedbackEnabled} onChange={e => change('feedbackEnabled', e.target.checked)} /> Bật AI nhận xét sau khi chấm</span></label><p>AI nhận xét chạy riêng cho từng mục và không thay đổi điểm phát âm. {caps?.feedback.configured ? 'Đã cấu hình.' : 'Chưa cấu hình AI; kết quả vẫn có hướng dẫn luyện tập cơ bản.'}</p><div className="speaking-actions"><button type="submit" disabled={busy} className="speaking-primary">Lưu bản nháp</button><button type="button" disabled={busy || (editing?.status === 'published' && JSON.stringify(draft) === JSON.stringify(editing))} className="speaking-primary" onClick={() => void publish()}>Xuất bản</button><button type="button" disabled={busy} onClick={() => { setEditing(null); setDraft(newDraft()); setBulkText(''); setError(''); setNotice(''); }}>Bài mới</button></div><div id="speaking-editor-feedback" className="speaking-editor-feedback" ref={editorFeedback} tabIndex={-1}>{error && <p role="alert" className="speaking-error">{error}</p>}{notice && <p role="status">{notice}</p>}{editing && <button type="button" disabled={busy} onClick={() => void perform(async () => { setSearch(''); setCatalogPage(1); setTab('lessons'); await reload('', 1); })}>Xem trong Kho bài</button>}<p>Lưu bản nháp đưa bài vào Kho bài. Xuất bản tự lưu nội dung hợp lệ trước khi mở bài cho học sinh.</p></div></form>}
    {tab === 'results' && <><div className="speaking-grid speaking-form"><label>Lớp<select value={grade} onChange={e => { setGrade(e.target.value); setPage(1); }}><option value="">Tất cả lớp</option>{Array.from({ length: 9 }, (_, i) => <option key={i} value={i + 1}>Lớp {i + 1}</option>)}</select></label><label>Dạng bài<select value={kind} onChange={e => { setKind(e.target.value); setPage(1); }}><option value="">Tất cả dạng bài</option>{Object.entries(KIND_LABELS).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></label></div><p>{results?.total || 0} lượt đã hoàn thành trong phạm vi quản lý.</p><div className="speaking-table-wrap"><table className="speaking-table"><thead><tr><th>Học sinh</th><th>Bài đọc</th><th>Lớp</th><th>Provider</th><th>Điểm</th><th>Hoàn thành</th><th>Chi tiết</th></tr></thead><tbody>{results?.items.map(item => <tr key={item.id}><td>{item.studentName}{item.className && ` · ${item.className}`}</td><td>{item.title}{item.isSession && ` · ${item.totalItems} mục`}</td><td>{item.grade}</td><td>{item.provider}</td><td>{item.score}/100</td><td>{new Date(item.completedAt).toLocaleString('vi-VN')}</td><td><button type="button" disabled={busy} onClick={() => void perform(async () => setReview(await adminRequest<SpeakingReviewData>(token, `/admin/results/${item.id}`)))}>Xem</button></td></tr>)}</tbody></table></div><div className="speaking-actions"><button type="button" disabled={page <= 1} onClick={() => setPage(p => p - 1)}>Trang trước</button><span>Trang {page}</span><button type="button" disabled={!results || page * results.pageSize >= results.total} onClick={() => setPage(p => p + 1)}>Trang sau</button><button type="button" onClick={() => { setGrade(''); setKind(''); setPage(1); }}>Xóa bộ lọc</button></div>{review && <SpeakingReview attempt={review} />}</>}
    {tab === 'config' && <div className="speaking-card"><h2>Trạng thái dịch vụ</h2>{caps?.providers.map(p => <p key={p.id}><strong>{p.label}</strong>: {p.configured ? 'Đã cấu hình' : 'Chưa cấu hình'} · tối đa {p.maxSeconds} giây</p>)}<p>AI nhận xét: {caps?.feedback.configured ? `Đã cấu hình · ${caps.feedback.provider || 'gemini'} · ${caps.feedback.model || ''} (${caps.feedback.mode})` : caps?.feedback.reason || 'Chưa cấu hình'}</p><p>Audio mẫu: {caps?.sampleTts?.configured ? caps.sampleTts.provider === 'azure' ? 'Azure TTS đã cấu hình' : 'TTS B đã cấu hình' : caps?.sampleTts?.reason || 'Kiểm tra cấu hình TTS của B.'}</p><p>Đặt AZURE_SPEECH_KEY + AZURE_SPEECH_REGION trên backend. SpeechSuper dùng SPEECHSUPER_APP_KEY + SPEECHSUPER_SECRET_KEY. Audio mẫu dùng Azure khi SPEAKING_SAMPLE_TTS_PROVIDER=azure; dùng cùng key và region Speech. TTS B vẫn dùng AI33_API_KEY/TTS_API_KEY khi chọn b. Không nhập khóa trên giao diện.</p><p>Hướng dẫn đầy đủ nằm trong docs/speaking-setup.md. Sau cấu hình, khởi động lại server rồi thử bản thu thật và đối chiếu giáo viên trước khi dùng điểm cho kỳ thi.</p></div>}
    {tab === 'config' && caps?.azureProsody && <div className="speaking-card" data-speaking-prosody-status><h3>Chấm ngữ điệu và nhịp điệu</h3><p>Azure prosody (Anh-Mỹ · en-US): <strong>{caps.azureProsody.enabled ? 'Đã bật' : 'Đang tắt'}</strong>.</p><p>Azure dùng một điểm prosody chung cho ngữ điệu, trọng âm, tốc độ và nhịp điệu. SpeechSuper cung cấp rhythm riêng; không ghép điểm của hai dịch vụ.</p><p>Đặt SPEAKING_AZURE_PROSODY=true trên backend rồi khởi động lại để bật. Lượt chấm cũ giữ nguyên; học sinh luyện lại sẽ nhận chỉ số được dịch vụ trả về.</p></div>}
  </section>;
}
